In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'USA301440.csv'

In [3]:
eu = pd.read_csv(f'{path}', names=["Date", "Time", "Open", "High", "Low", "Close", "Volume"])

In [4]:
def clean(File):  
    """We need only 'Date' and 'Close' Columns from the dataset """
    #File.drop(File.loc[:, ["Time", "Open", "High", "Low", "Volume"]], inplace=True, axis=1)
    File = File.loc[:,['Date', 'Close']]


    """Converting the 'Date' column from a string to a datetime"""
    File['Date'] = pd.to_datetime(File['Date'])
    
    """Assigning new columns for our next calculations"""
    File['Year'] = File.Date.dt.year
    File['Week_day'] =File.Date.dt.weekday
    File['Day_name'] = File.Date.dt.weekday_name
    File['Week'] = File.Date.dt.weekofyear
    File['Returns'] = np.log(File.Close/File.Close.shift(1))
    return File

In [5]:
cols = []
def display_all(df):
    with pd.option_context("display.max_rows", 14000, "display.max_columns", 1000): 
        display(df)

def feat(File):
    
    for i in range(0, len(File)):
        year = File.loc[i,'Year']
        week = File.loc[i,'Week']
        day = File.loc[i,'Week_day']
        lags = 5
        cols = []
        for lag in range(1, lags+1):
                   
            col = 'feat_%s' % (lag)
          
            try:
                File.loc[i, col] = File.loc[((File.Week_day == day)&(File.Week == week)&(File.Year== (year - lag)), 'Returns')].values[0]
            except:
                File.loc[i, col] = None
            
            
            cols.append(col)
            
    File.dropna(inplace=True)
    File[cols] = np.where(File[cols] > 0, 1, 0)
    File['Direction'] = np.where(File['Returns'] > 0, 1, -1)
    return display_all(File)

In [6]:
data = clean(eu)

In [7]:
feat(data)

,Date,Close,Year,Week_day,Day_name,Week,Returns,feat_1,feat_2,feat_3,feat_4,feat_5,Direction
1323,2015-12-16,17709.0,2015,2,Wednesday,51,0.008905,1,1,0,0,1,1
1324,2015-12-17,17428.0,2015,3,Thursday,51,-0.015995,1,1,1,1,1,-1
1338,2016-01-08,16328.0,2016,4,Friday,1,-0.012053,0,1,1,0,0,-1
1339,2016-01-11,16373.0,2016,0,Monday,2,0.002752,0,0,0,1,0,1
1340,2016-01-12,16439.0,2016,1,Tuesday,2,0.004023,0,1,0,1,1,1
1341,2016-01-13,16168.0,2016,2,Wednesday,2,-0.016623,1,0,1,1,1,-1
1342,2016-01-14,16365.0,2016,3,Thursday,2,0.012111,1,0,1,1,0,1
1343,2016-01-15,15997.0,2016,4,Friday,2,-0.022744,0,0,1,0,1,-1
1344,2016-01-18,15989.0,2016,0,Monday,3,-0.000500,0,0,1,1,0,-1
1345,2016-01-19,15975.0,2016,1,Tuesday,3,-0.000876,0,1,1,1,1,-1
1346,2016-01-20,15794.0,2016,2,Wednesday,3,-0.011395,0,1,0,1,0,-1
1347,2016-01-21,15841.0,2016,3,Thursday,3,0.002971,0,0,1,1,0,1
1348,2016-01-22,16086.0,2016,4,Friday,3,0.015348,1,1,1,1,1,1
1349,2016-01-25,15900.0,2016,0,Monday,4,-0.011630,0,0,1,0,1,-1
1350,2016-01-26,16072.0,2016,1,Tuesday,4,0.010760,1,0,1,1,0,1
1351,2016-01-27,15951.0,2016,2,Wednesday,4,-0.007557,1,0,1,1,1,-1
1352,2016-01-28,16058.0,2016,3,Thursday,4,0.006686,1,0,1,0,0,1
1353,2016-01-29,16430.0,2016,4,Friday,4,0.022902,0,0,1,0,0,1
1354,2016-02-01,16400.0,2016,0,Monday,5,-0.001828,1,0,1,0,1,-1
1355,2016-02-02,16157.0,2016,1,Tuesday,5,-0.014928,0,1,1,0,1,-1
1356,2016-02-03,16344.0,2016,2,Wednesday,5,0.011507,0,0,0,1,1,1
1357,2016-02-04,16384.0,2016,3,Thursday,5,0.002444,1,1,0,1,1,1
1358,2016-02-05,16207.0,2016,4,Friday,5,-0.010862,0,0,1,1,1,-1
1359,2016-02-08,16034.0,2016,0,Monday,6,-0.010732,1,0,0,0,1,-1
1360,2016-02-09,16009.0,2016,1,Tuesday,6,-0.001560,1,1,1,1,1,-1
1361,2016-02-10,15879.0,2016,2,Wednesday,6,-0.008154,0,1,0,0,0,-1
1362,2016-02-11,15675.0,2016,3,Thursday,6,-0.012930,1,1,0,1,0,-1
1363,2016-02-12,15961.0,2016,4,Friday,6,0.018081,0,1,1,0,1,1
1364,2016-02-15,16151.0,2016,0,Monday,7,0.011834,0,1,0,1,0,1
1365,2016-02-16,16168.0,2016,1,Tuesday,7,0.001052,1,1,1,1,0,1
1366,2016-02-17,16475.0,2016,2,Wednesday,7,0.018810,1,1,0,0,1,1
1367,2016-02-18,16425.0,2016,3,Thursday,7,-0.003040,1,1,0,1,1,-1
1368,2016-02-19,16385.0,2016,4,Friday,7,-0.002438,1,1,0,1,1,-1
1369,2016-02-22,16549.0,2016,0,Monday,8,0.009959,0,1,1,1,0,1
1370,2016-02-23,16403.0,2016,1,Tuesday,8,-0.008861,1,0,1,0,0,-1
1371,2016-02-24,16523.0,2016,2,Wednesday,8,0.007289,0,0,0,0,0,1
1372,2016-02-25,16685.0,2016,3,Thursday,8,0.009757,0,1,0,1,0,1
1373,2016-02-26,16623.0,2016,4,Friday,8,-0.003723,1,0,1,0,1,-1
1374,2016-02-29,16507.0,2016,0,Monday,9,-0.007003,0,1,0,1,1,-1
1375,2016-03-01,16852.0,2016,1,Tuesday,9,0.020685,1,1,1,1,0,1
1376,2016-03-02,16869.0,2016,2,Wednesday,9,0.001008,0,0,1,0,1,1
1377,2016-03-03,16936.0,2016,3,Thursday,9,0.003964,1,1,0,1,1,1
1378,2016-03-04,16981.0,2016,4,Friday,9,0.002654,0,1,1,0,0,1
1379,2016-03-07,17060.0,2016,0,Monday,10,0.004641,1,0,1,0,0,1
1380,2016-03-08,16980.0,2016,1,Tuesday,10,-0.004700,0,1,1,0,1,-1
1381,2016-03-09,17012.0,2016,2,Wednesday,10,0.001883,0,0,1,1,0,1
1382,2016-03-10,16990.0,2016,3,Thursday,10,-0.001294,1,1,1,1,0,-1
1383,2016-03-11,17183.0,2016,4,Friday,10,0.011296,0,1,1,1,1,1
1384,2016-03-14,17216.0,2016,0,Monday,11,0.001919,1,0,1,1,0,1
1385,2016-03-15,17241.0,2016,1,Tuesday,11,0.001451,0,0,1,1,0,1
1386,2016-03-16,17329.0,2016,2,Wednesday,11,0.005091,0,1,1,0,0,1
1387,2016-03-17,17491.0,2016,3,Thursday,11,0.009305,1,0,1,1,1,1
1388,2016-03-18,17580.0,2016,4,Friday,11,0.005075,0,0,1,1,1,1
1389,2016-03-21,17629.0,2016,0,Monday,12,0.002783,1,1,0,1,1,1
1390,2016-03-22,17595.0,2016,1,Tuesday,12,-0.001931,0,1,0,0,0,-1
1391,2016-03-23,17517.0,2016,2,Wednesday,12,-0.004443,1,0,1,0,1,-1
1392,2016-03-24,17551.0,2016,3,Thursday,12,0.001939,0,1,0,0,1,1
1393,2016-03-28,17538.0,2016,0,Monday,13,-0.000741,0,0,0,1,0,-1
1394,2016-03-29,17635.0,2016,1,Tuesday,13,0.005516,0,1,1,0,1,1
1395,2016-03-30,17723.0,2016,2,Wednesday,13,0.004978,0,0,0,0,1,1
1396,2016-03-31,17701.0,2016,3,Thursday,13,-0.001242,0,0,1,1,0,-1
1398,2016-04-04,17719.0,2016,0,Monday,14,-0.004617,1,1,0,1,1,-1
1399,2016-04-05,17632.0,2016,1,Tuesday,14,-0.004922,0,1,1,0,0,-1
1400,2016-04-06,17709.0,2016,2,Wednesday,14,0.004358,0,1,0,0,1,1
1401,2016-04-07,17540.0,2016,3,Thursday,14,-0.009589,1,1,1,0,0,-1
1403,2016-04-11,17543.0,2016,0,Monday,15,-0.001481,1,0,1,0,0,-1
1404,2016-04-12,17721.0,2016,1,Tuesday,15,0.010095,0,0,1,0,0,1
1405,2016-04-13,17916.0,2016,2,Wednesday,15,0.010944,1,1,1,1,0,1
1406,2016-04-14,17931.0,2016,3,Thursday,15,0.000837,1,0,1,1,1,1
1407,2016-04-15,17895.0,2016,4,Friday,15,-0.002010,1,0,0,0,1,-1
1408,2016-04-18,17987.0,2016,0,Monday,16,0.005128,0,1,0,1,0,1
1409,2016-04-19,18043.0,2016,1,Tuesday,16,0.003109,1,1,1,1,1,1
1410,2016-04-20,18122.0,2016,2,Wednesday,16,0.004369,1,1,0,0,1,1
1411,2016-04-21,17964.0,2016,3,Thursday,16,-0.008757,1,1,0,0,0,-1
1413,2016-04-25,17983.0,2016,0,Monday,17,-0.000667,1,1,1,0,0,-1
1414,2016-04-26,17964.0,2016,1,Tuesday,17,-0.001057,0,1,1,1,1,-1
1415,2016-04-27,18050.0,2016,2,Wednesday,17,0.004776,1,1,0,1,1,1
1416,2016-04-28,17848.0,2016,3,Thursday,17,-0.011254,1,0,1,1,1,-1
1417,2016-04-29,17794.0,2016,4,Friday,17,-0.003030,1,0,0,1,1,-1
1418,2016-05-02,17885.0,2016,0,Monday,18,0.005101,0,1,1,1,1,1
1419,2016-05-03,17759.0,2016,1,Tuesday,18,-0.007070,1,1,1,1,0,-1
1420,2016-05-04,17652.0,2016,2,Wednesday,18,-0.006043,0,1,0,0,0,-1
1421,2016-05-05,17641.0,2016,3,Thursday,18,-0.000623,0,0,1,0,0,-1
1422,2016-05-06,17737.0,2016,4,Friday,18,0.005427,1,0,1,0,1,1
1423,2016-05-09,17713.0,2016,0,Monday,19,-0.001354,1,1,1,1,1,-1
1424,2016-05-10,17885.0,2016,1,Tuesday,19,0.009664,0,0,1,0,1,1
1425,2016-05-11,17711.0,2016,2,Wednesday,19,-0.009776,0,1,1,0,0,-1
1426,2016-05-12,17717.0,2016,3,Thursday,19,0.000339,1,1,0,1,1,1
1427,2016-05-13,17539.0,2016,4,Friday,19,-0.010098,1,1,1,1,0,-1
1428,2016-05-16,17699.0,2016,0,Monday,20,0.009081,0,1,0,0,0,1
1429,2016-05-17,17524.0,2016,1,Tuesday,20,-0.009937,0,1,1,0,0,-1
1430,2016-05-18,17518.0,2016,2,Wednesday,20,-0.000342,0,0,1,0,1,-1
1431,2016-05-19,17443.0,2016,3,Thursday,20,-0.004291,1,0,0,0,1,-1
1432,2016-05-20,17509.0,2016,4,Friday,20,0.003777,1,1,1,0,0,1
1433,2016-05-23,17490.0,2016,0,Monday,21,-0.001086,1,1,0,1,0,-1
1434,2016-05-24,17714.0,2016,1,Tuesday,21,0.012726,1,0,1,0,0,1
1435,2016-05-25,17849.0,2016,2,Wednesday,21,0.007592,0,1,0,0,1,1
1436,2016-05-26,17840.0,2016,3,Thursday,21,-0.000504,1,1,0,1,1,-1
1437,2016-05-27,17866.0,2016,4,Friday,21,0.001456,0,1,1,0,1,1
1438,2016-05-30,17910.5,2016,0,Monday,22,0.002488,0,1,1,1,1,1
1439,2016-05-31,17779.0,2016,1,Tuesday,22,-0.007369,0,1,1,1,1,-1
1440,2016-06-01,17780.0,2016,2,Wednesday,22,0.000056,1,0,0,0,0,1
1441,2016-06-02,17832.0,2016,3,Thursday,22,0.002920,1,1,1,0,0,1
1442,2016-06-03,17808.0,2016,4,Friday,22,-0.001347,0,1,0,0,0,-1
1443,2016-06-06,17923.0,2016,0,Monday,23,0.006437,1,1,1,0,0,1
1444,2016-06-07,17940.0,2016,1,Tuesday,23,0.000948,0,0,0,1,1,1
1445,2016-06-08,17993.0,2016,2,Wednesday,23,0.002950,1,0,0,1,0,1
1446,2016-06-09,17980.0,2016,3,Thursday,23,-0.000723,0,1,1,1,1,-1
1447,2016-06-10,17870.0,2016,4,Friday,23,-0.006137,0,1,1,1,0,-1
1448,2016-06-13,17717.5,2016,0,Monday,24,-0.008570,0,0,1,0,1,-1
1449,2016-06-14,17655.5,2016,1,Tuesday,24,-0.003506,0,1,0,1,1,-1
1450,2016-06-15,17629.0,2016,2,Wednesday,24,-0.001502,1,0,0,0,0,-1
1451,2016-06-16,17722.0,2016,3,Thursday,24,0.005262,1,0,1,1,1,1
1452,2016-06-17,17649.0,2016,4,Friday,24,-0.004128,0,1,0,1,1,-1
1453,2016-06-20,17835.0,2016,0,Monday,25,0.010484,0,0,1,0,1,1
1454,2016-06-21,17821.0,2016,1,Tuesday,25,-0.000785,1,1,1,1,1,-1
1455,2016-06-22,17782.0,2016,2,Wednesday,25,-0.002191,0,1,0,1,0,-1
1456,2016-06-23,18060.5,2016,3,Thursday,25,0.015541,1,1,0,0,1,1
1457,2016-06-24,17363.5,2016,4,Friday,25,-0.039357,0,1,1,1,0,-1
1458,2016-06-27,17082.0,2016,0,Monday,26,-0.016345,1,0,0,0,1,-1
1459,2016-06-28,17388.0,2016,1,Tuesday,26,0.017755,1,0,1,1,1,1
1460,2016-06-29,17782.0,2016,2,Wednesday,26,0.022406,0,1,1,1,1,1
1461,2016-06-30,17887.0,2016,3,Thursday,26,0.005887,0,0,1,0,1,1
1462,2016-07-01,17964.0,2016,4,Friday,26,0.004296,1,0,0,1,1,1
1463,2016-07-04,17970.5,2016,0,Monday,27,0.000362,0,0,1,0,1,1
1464,2016-07-05,17860.5,2016,1,Tuesday,27,-0.006140,0,1,0,1,0,-1
1465,2016-07-06,17914.0,2016,2,Wednesday,27,0.002991,1,1,1,0,1,1
1466,2016-07-07,17898.5,2016,3,Thursday,27,-0.000866,0,1,1,0,1,-1
1467,2016-07-08,18119.0,2016,4,Friday,27,0.012244,0,0,1,0,0,1
1468,2016-07-11,18230.5,2016,0,Monday,28,0.006135,1,0,1,0,0,1
1469,2016-07-12,18353.5,2016,1,Tuesday,28,0.006724,1,0,1,0,0,1
1470,2016-07-13,18372.0,2016,2,Wednesday,28,0.001007,0,1,1,0,0,1
1471,2016-07-14,18505.5,2016,3,Thursday,28,0.007240,1,0,1,0,0,1
1472,2016-07-15,18497.0,2016,4,Friday,28,-0.000459,1,1,0,1,1,-1
1473,2016-07-18,18547.0,2016,0,Monday,29,0.002699,1,1,1,0,0,1
1474,2016-07-19,18562.0,2016,1,Tuesday,29,0.000808,1,1,0,1,1,1
1475,2016-07-20,18597.0,2016,2,Wednesday,29,0.001884,1,1,1,1,1,1
1476,2016-07-21,18511.0,2016,3,Thursday,29,-0.004635,1,0,1,0,1,-1
1477,2016-07-22,18549.0,2016,4,Friday,29,0.002051,0,1,1,0,0,1
1478,2016-07-25,18498.5,2016,0,Monday,30,-0.002726,0,0,0,0,1,-1
1479,2016-07-26,18487.0,2016,1,Tuesday,30,-0.000622,0,1,1,0,0,-1
1480,2016-07-27,18476.0,2016,2,Wednesday,30,-0.000595,0,1,0,1,0,-1
1481,2016-07-28,18450.5,2016,3,Thursday,30,-0.001381,0,0,0,1,0,-1
1482,2016-07-29,18446.5,2016,4,Friday,30,-0.000217,0,0,0,1,0,-1
1483,2016-08-01,18406.0,2016,0,Monday,31,-0.002198,0,1,0,0,0,-1
1484,2016-08-02,18320.0,2016,1,Tuesday,31,-0.004683,1,0,1,0,0,-1
1485,2016-08-03,18341.0,2016,2,Wednesday,31,0.001146,1,0,0,0,1,1
1486,2016-08-04,18347.0,2016,3,Thursday,31,0.000327,1,0,1,0,0,1
1487,2016-08-05,18520.5,2016,4,Friday,31,0.009412,0,0,1,1,1,1
1488,2016-08-08,18524.5,2016,0,Monday,32,0.000216,0,1,0,1,0,1
1489,2016-08-09,18529.0,2016,1,Tuesday,32,0.000243,0,0,0,1,1,1
1490,2016-08-10,18493.5,2016,2,Wednesday,32,-0.001918,1,1,0,0,0,-1
1491,2016-08-11,18608.0,2016,3,Thursday,32,0.006172,0,0,1,1,1,1
1492,2016-08-12,18565.0,2016,4,Friday,32,-0.002314,0,1,0,1,1,-1
1493,2016-08-15,18629.0,2016,0,Monday,33,0.003441,1,1,1,0,1,1
1494,2016-08-16,18577.0,2016,1,Tuesday,33,-0.002795,0,1,1,0,0,-1
1495,2016-08-17,18572.0,2016,2,Wednesday,33,-0.000269,0,1,0,1,1,-1
1496,2016-08-18,18581.5,2016,3,Thursday,33,0.000511,1,1,0,1,0,1
1497,2016-08-19,18558.0,2016,4,Friday,33,-0.001265,1,0,0,1,0,-1
1498,2016-08-22,18535.0,2016,0,Monday,34,-0.001240,1,1,0,0,1,-1
1499,2016-08-23,18552.0,2016,1,Tuesday,34,0.000917,0,1,0,0,1,1
1500,2016-08-24,18489.5,2016,2,Wednesday,34,-0.003375,0,1,0,0,1,-1
1501,2016-08-25,18470.0,2016,3,Thursday,34,-0.001055,0,1,1,0,0,-1
1502,2016-08-26,18401.0,2016,4,Friday,34,-0.003743,0,0,1,1,1,-1
1503,2016-08-29,18514.0,2016,0,Monday,35,0.006122,0,1,0,0,1,1
1504,2016-08-30,18454.0,2016,1,Tuesday,35,-0.003246,1,1,0,0,0,-1
1505,2016-08-31,18394.5,2016,2,Wednesday,35,-0.003229,1,0,1,0,1,-1
1506,2016-09-01,18397.0,2016,3,Thursday,35,0.000136,1,0,1,0,0,1
1507,2016-09-02,18486.5,2016,4,Friday,35,0.004853,1,0,0,1,0,1
1508,2016-09-05,18492.0,2016,0,Monday,36,0.000297,0,1,1,1,0,1
1509,2016-09-06,18536.0,2016,1,Tuesday,36,0.002377,0,0,0,0,1,1
1510,2016-09-07,18515.5,2016,2,Wednesday,36,-0.001107,1,0,1,1,1,-1
1511,2016-09-08,18459.0,2016,3,Thursday,36,-0.003056,1,1,0,1,0,-1
1512,2016-09-09,18040.5,2016,4,Friday,36,-0.022933,0,1,1,1,0,-1
1513,2016-09-12,18318.0,2016,0,Monday,37,0.015265,1,0,1,0,1,1
1514,2016-09-13,18103.5,2016,1,Tuesday,37,-0.011779,1,0,1,1,1,-1
1515,2016-09-14,18014.0,2016,2,Wednesday,37,-0.004956,0,1,1,1,1,-1
1516,2016-09-15,18190.0,2016,3,Thursday,37,0.009723,1,0,0,1,1,1
1517,2016-09-16,18133.5,2016,4,Friday,37,-0.003111,1,0,1,1,1,-1
1518,2016-09-19,18139.0,2016,0,Monday,38,0.000303,0,1,1,0,0,1
1519,2016-09-20,18121.0,2016,1,Tuesday,38,-0.000993,1,1,1,1,1,-1
1520,2016-09-21,18302.0,2016,2,Wednesday,38,0.009939,1,1,1,0,0,1
1521,2016-09-22,18386.5,2016,3,Thursday,38,0.004606,0,1,0,1,0,1
1522,2016-09-23,18275.5,2016,4,Friday,38,-0.006055,0,1,0,0,0,-1
1523,2016-09-26,18104.0,2016,0,Monday,39,-0.009428,1,0,0,0,1,-1
1524,2016-09-27,18217.0,2016,1,Tuesday,39,0.006222,0,0,0,0,1,1
1525,2016-09-28,18315.5,2016,2,Wednesday,39,0.005392,0,1,0,0,0,1
1526,2016-09-29,18177.5,2016,3,Thursday,39,-0.007563,0,0,1,1,1,-1
1527,2016-09-30,18291.5,2016,4,Friday,39,0.006252,1,1,0,0,0,1
1528,2016-10-03,18252.5,2016,0,Monday,40,-0.002134,0,0,0,1,0,-1
1529,2016-10-04,18168.0,2016,1,Tuesday,40,-0.004640,1,0,1,0,1,-1
1530,2016-10-05,18282.0,2016,2,Wednesday,40,0.006255,1,0,0,1,1,1
1531,2016-10-06,18269.0,2016,3,Thursday,40,-0.000711,1,0,0,1,1,-1
1532,2016-10-07,18235.5,2016,4,Friday,40,-0.001835,1,1,1,1,0,-1
1533,2016-10-10,18342.5,2016,0,Monday,41,0.005851,1,0,0,0,1,1
1534,2016-10-11,18139.0,2016,1,Tuesday,41,-0.011156,0,0,0,0,0,-1
1535,2016-10-12,18104.0,2016,2,Wednesday,41,-0.001931,1,1,1,0,1,-1
1536,2016-10-13,18106.0,2016,3,Thursday,41,0.000110,1,0,1,1,0,1
1537,2016-10-14,18141.0,2016,4,Friday,41,0.001931,1,0,1,0,1,1
1538,2016-10-17,18068.5,2016,0,Monday,42,-0.004004,1,0,1,1,0,-1
1539,2016-10-18,18140.0,2016,1,Tuesday,42,0.003949,0,1,0,1,1,1
1540,2016-10-19,18197.0,2016,2,Wednesday,42,0.003137,0,0,1,1,0,1
1541,2016-10-20,18180.5,2016,3,Thursday,42,-0.000907,1,1,1,0,1,-1
1542,2016-10-21,18143.5,2016,4,Friday,42,-0.002037,1,1,1,0,1,-1
1543,2016-10-24,18219.0,2016,0,Monday,43,0.004153,0,1,1,1,1,1
1544,2016-10-25,18162.5,2016,1,Tuesday,43,-0.003106,0,1,1,0,0,-1
1545,2016-10-26,18207.5,2016,2,Wednesday,43,0.002475,0,0,0,0,1,1
1546,2016-10-27,18188.0,2016,3,Thursday,43,-0.001072,1,1,1,1,1,-1
1547,2016-10-28,18175.5,2016,4,Friday,43,-0.000688,1,1,1,1,1,-1
1548,2016-10-31,18162.0,2016,0,Monday,44,-0.000743,0,1,1,0,0,-1
1549,2016-11-01,18007.0,2016,1,Tuesday,44,-0.008571,0,1,1,1,0,-1
1550,2016-11-02,17945.0,2016,2,Wednesday,44,-0.003449,1,0,0,0,1,-1
1551,2016-11-03,17925.0,2016,3,Thursday,44,-0.001115,1,1,0,1,1,-1
1552,2016-11-04,17883.5,2016,4,Friday,44,-0.002318,0,1,1,0,0,-1
1553,2016-11-07,18284.5,2016,0,Monday,45,0.022175,1,0,1,1,1,1
1554,2016-11-08,18343.0,2016,1,Tuesday,45,0.003194,1,1,0,1,1,1
1555,2016-11-09,18586.0,2016,2,Wednesday,45,0.013161,0,1,1,0,0,1
1556,2016-11-10,18821.0,2016,3,Thursday,45,0.012565,0,1,0,0,1,1
1557,2016-11-11,18840.0,2016,4,Friday,45,0.001009,1,1,1,0,1,1
1558,2016-11-14,18875.0,2016,0,Monday,46,0.001856,0,1,1,1,0,1
1559,2016-11-15,18927.5,2016,1,Tuesday,46,0.002778,1,1,0,0,0,1
1560,2016-11-16,18857.0,2016,2,Wednesday,46,-0.003732,0,0,1,0,0,-1
1561,2016-11-17,18902.0,2016,3,Thursday,46,0.002384,0,1,1,0,0,1
1562,2016-11-18,18876.5,2016,4,Friday,46,-0.001350,0,1,1,1,1,-1
1563,2016-11-21,18945.5,2016,0,Monday,47,0.003649,1,1,1,1,0,1
1564,2016-11-22,19027.0,2016,1,Tuesday,47,0.004293,1,1,0,1,0,1
1565,2016-11-23,19086.5,2016,2,Wednesday,47,0.003122,1,0,0,1,0,1
1566,2016-11-24,19140.5,2016,3,Thursday,47,0.002825,1,1,1,1,0,1
1567,2016-11-25,19149.0,2016,4,Friday,47,0.000444,1,1,1,1,0,1
1568,2016-11-28,19112.0,2016,0,Monday,48,-0.001934,0,1,1,0,1,-1
1569,2016-11-29,19123.0,2016,1,Tuesday,48,0.000575,1,1,0,0,1,1
1570,2016-11-30,19143.5,2016,2,Wednesday,48,0.001071,1,1,1,1,1,1
1571,2016-12-01,19196.5,2016,3,Thursday,48,0.002765,1,1,1,1,0,1
1572,2016-12-02,19166.0,2016,4,Friday,48,-0.001590,0,0,0,0,1,-1
1573,2016-12-05,19219.5,2016,0,Monday,49,0.002788,0,0,0,0,1,1
1574,2016-12-06,19246.5,2016,1,Tuesday,49,0.001404,1,1,0,0,1,1
1575,2016-12-07,19519.5,2016,2,Wednesday,49,0.014085,0,1,0,1,1,1
1576,2016-12-08,19619.5,2016,3,Thursday,49,0.005110,0,0,0,1,0,1
1577,2016-12-09,19765.0,2016,4,Friday,49,0.007389,1,1,1,1,1,1
1578,2016-12-12,19794.0,2016,0,Monday,50,0.001466,0,0,1,1,0,1
1579,2016-12-13,19914.5,2016,1,Tuesday,50,0.006069,0,0,0,1,0,1
1580,2016-12-14,19812.0,2016,2,Wednesday,50,-0.005160,0,0,0,0,0,-1
1581,2016-12-15,19868.0,2016,3,Thursday,50,0.002823,1,1,0,0,1,1
1582,2016-12-16,19847.0,2016,4,Friday,50,-0.001058,0,0,1,0,0,-1
1583,2016-12-19,19893.5,2016,0,Monday,51,0.002340,1,0,1,1,0,1
1584,2016-12-20,19966.0,2016,1,Tuesday,51,0.003638,1,0,0,1,1,1
1585,2016-12-21,19929.0,2016,2,Wednesday,51,-0.001855,1,1,1,0,0,-1
1586,2016-12-22,19920.0,2016,3,Thursday,51,-0.000452,0,1,1,1,1,-1
1587,2016-12-23,19927.5,2016,4,Friday,51,0.000376,0,1,1,0,1,1
1595,2017-01-06,19961.0,2017,4,Friday,1,0.003262,0,0,1,1,0,1
1596,2017-01-09,19892.0,2017,0,Monday,2,-0.003463,1,0,0,0,1,-1
1597,2017-01-10,19870.5,2017,1,Tuesday,2,-0.001081,1,0,1,0,1,-1
1598,2017-01-11,19952.0,2017,2,Wednesday,2,0.004093,0,1,0,1,1,1
1599,2017-01-12,19887.0,2017,3,Thursday,2,-0.003263,1,1,0,1,1,-1
1600,2017-01-13,19907.5,2017,4,Friday,2,0.001030,0,0,0,1,0,1
1601,2017-01-16,19857.5,2017,0,Monday,3,-0.002515,0,0,0,1,1,-1
1602,2017-01-17,19815.0,2017,1,Tuesday,3,-0.002143,0,0,1,1,1,-1
1603,2017-01-18,19788.0,2017,2,Wednesday,3,-0.001364,0,0,1,0,1,-1
1604,2017-01-19,19711.5,2017,3,Thursday,3,-0.003873,1,0,0,1,1,-1
1605,2017-01-20,19816.5,2017,4,Friday,3,0.005313,1,1,1,1,1,1
1606,2017-01-23,19793.5,2017,0,Monday,4,-0.001161,0,0,0,1,0,-1
1607,2017-01-24,19919.0,2017,1,Tuesday,4,0.006320,1,1,0,1,1,1
1608,2017-01-25,20072.5,2017,2,Wednesday,4,0.007677,0,1,0,1,1,1
1609,2017-01-26,20118.5,2017,3,Thursday,4,0.002289,1,1,0,1,0,1
1610,2017-01-27,20074.0,2017,4,Friday,4,-0.002214,1,0,0,1,0,-1
1611,2017-01-30,19951.0,2017,0,Monday,5,-0.006146,0,1,0,1,0,-1
1612,2017-01-31,19891.0,2017,1,Tuesday,5,-0.003012,0,0,1,1,0,-1
1613,2017-02-01,19888.5,2017,2,Wednesday,5,-0.000126,1,0,0,0,1,-1
1614,2017-02-02,19880.0,2017,3,Thursday,5,-0.000427,1,1,1,0,1,-1
1615,2017-02-03,20055.0,2017,4,Friday,5,0.008764,0,0,0,1,1,1
1616,2017-02-06,20041.0,2017,0,Monday,6,-0.000698,0,1,0,0,0,-1
1617,2017-02-07,20075.0,2017,1,Tuesday,6,0.001695,0,1,1,1,1,1
1618,2017-02-08,20051.0,2017,2,Wednesday,6,-0.001196,0,0,1,0,0,-1
1619,2017-02-09,20182.0,2017,3,Thursday,6,0.006512,0,1,1,0,1,1
1620,2017-02-10,20265.0,2017,4,Friday,6,0.004104,1,0,1,1,0,1
1621,2017-02-13,20431.5,2017,0,Monday,7,0.008183,1,0,1,0,1,1
1622,2017-02-14,20523.5,2017,1,Tuesday,7,0.004493,1,1,1,1,1,1
1623,2017-02-15,20646.0,2017,2,Wednesday,7,0.005951,1,1,1,0,0,1
1624,2017-02-16,20614.5,2017,3,Thursday,7,-0.001527,0,1,1,0,1,-1
1625,2017-02-17,20603.5,2017,4,Friday,7,-0.000534,0,1,1,0,1,-1
1626,2017-02-20,20659.5,2017,0,Monday,8,0.002714,1,0,1,1,1,1
1627,2017-02-21,20709.0,2017,1,Tuesday,8,0.002393,0,1,0,1,0,1
1628,2017-02-22,20781.5,2017,2,Wednesday,8,0.003495,1,0,0,0,0,1
1629,2017-02-23,20819.5,2017,3,Thursday,8,0.001827,1,0,1,0,1,1
1630,2017-02-24,20801.5,2017,4,Friday,8,-0.000865,0,1,0,1,0,-1
1631,2017-02-27,20812.0,2017,0,Monday,9,0.000505,0,0,1,0,1,1
1632,2017-02-28,20838.0,2017,1,Tuesday,9,0.001248,1,1,1,1,1,1
1633,2017-03-01,21096.0,2017,2,Wednesday,9,0.012305,1,0,0,1,0,1
1634,2017-03-02,20997.5,2017,3,Thursday,9,-0.004680,1,1,1,0,1,-1
1635,2017-03-03,20989.0,2017,4,Friday,9,-0.000405,1,0,1,1,0,-1
1636,2017-03-06,20926.0,2017,0,Monday,10,-0.003006,1,1,0,1,0,-1
1637,2017-03-07,20918.5,2017,1,Tuesday,10,-0.000358,0,0,1,1,0,-1
1638,2017-03-08,20851.5,2017,2,Wednesday,10,-0.003208,1,0,0,1,1,-1
1639,2017-03-09,20874.5,2017,3,Thursday,10,0.001102,0,1,1,1,1,1
1640,2017-03-10,20885.5,2017,4,Friday,10,0.000527,1,0,1,1,1,1
1641,2017-03-13,20874.5,2017,0,Monday,11,-0.000527,1,1,0,1,1,-1
1642,2017-03-14,20842.8,2017,1,Tuesday,11,-0.001520,1,0,0,1,1,-1
1643,2017-03-15,20929.4,2017,2,Wednesday,11,0.004146,1,0,1,1,0,1
1644,2017-03-16,20932.3,2017,3,Thursday,11,0.000139,1,1,0,1,1,1
1645,2017-03-17,20908.0,2017,4,Friday,11,-0.001162,1,0,0,1,1,-1
1646,2017-03-20,20908.0,2017,0,Monday,12,0.000000,1,1,1,0,1,-1
1647,2017-03-21,20660.5,2017,1,Tuesday,12,-0.011908,0,0,1,0,0,-1
1648,2017-03-22,20643.7,2017,2,Wednesday,12,-0.000813,0,1,0,1,0,-1
1649,2017-03-23,20658.0,2017,3,Thursday,12,0.000692,1,0,1,0,0,1
1651,2017-03-27,20568.0,2017,0,Monday,13,-0.002646,0,0,0,0,1,-1
1652,2017-03-28,20686.5,2017,1,Tuesday,13,0.005745,1,0,1,1,0,1
1653,2017-03-29,20646.5,2017,2,Wednesday,13,-0.001936,1,0,0,0,0,-1
1654,2017-03-30,20726.5,2017,3,Thursday,13,0.003867,0,0,0,1,1,1
1656,2017-04-03,20641.0,2017,0,Monday,14,-0.001307,0,1,1,0,1,-1
1657,2017-04-04,20708.5,2017,1,Tuesday,14,0.003265,0,0,1,1,0,1
1658,2017-04-05,20623.5,2017,2,Wednesday,14,-0.004113,1,0,1,0,0,-1

In [8]:
cols = ['feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5']
data[cols + ['Direction']].head()

      feat_1  feat_2  feat_3  feat_4  feat_5  Direction
1323       1       1       0       0       1          1
1324       1       1       1       1       1         -1
1338       0       1       1       0       0         -1
1339       0       0       0       1       0          1
1340       0       1       0       1       1          1

## *MACHINE LEARNING*

#### **Random Forest**

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

C:\Users\Siseng Consulting\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [10]:
split = int(len(data) * 0.75)
train = data.iloc[:split].copy()
test = data.iloc[split:].copy()

In [11]:
model = RandomForestClassifier(n_estimators=100,n_jobs=-1, min_samples_leaf=45)
#train[cols] = sc.fit_transform(train[cols])
#test[cols] = sc.transform(test[cols])
model.fit(train[cols], train['Direction'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=45, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [12]:
accuracy_score(train['Direction'], model.predict(train[cols]))

0.5495145631067961

In [13]:
test['Position'] = model.predict(test[cols])
accuracy_score(test['Direction'], test['Position'])

0.5697674418604651