In [1]:
import pandas as pd
import numpy as np

In [3]:
path = 'GER301440.csv'

In [4]:
eu = pd.read_csv(f'{path}', names=["Date", "Time", "Open", "High", "Low", "Close", "Volume"])

In [5]:
def clean(File):  
    """We need only 'Date' and 'Close' Columns from the dataset """
    #File.drop(File.loc[:, ["Time", "Open", "High", "Low", "Volume"]], inplace=True, axis=1)
    File = File.loc[:,['Date', 'Close']]


    """Converting the 'Date' column from a string to a datetime"""
    File['Date'] = pd.to_datetime(File['Date'])
    
    """Assigning new columns for our next calculations"""
    File['Year'] = File.Date.dt.year
    File['Week_day'] =File.Date.dt.weekday
    File['Day_name'] = File.Date.dt.weekday_name
    File['Week'] = File.Date.dt.weekofyear
    File['Returns'] = np.log(File.Close/File.Close.shift(1))
    return File

In [6]:
cols = []
def display_all(df):
    with pd.option_context("display.max_rows", 14000, "display.max_columns", 1000): 
        display(df)

def feat(File):
    
    for i in range(0, len(File)):
        year = File.loc[i,'Year']
        week = File.loc[i,'Week']
        day = File.loc[i,'Week_day']
        lags = 5
        cols = []
        for lag in range(1, lags+1):
                   
            col = 'feat_%s' % (lag)
          
            try:
                File.loc[i, col] = File.loc[((File.Week_day == day)&(File.Week == week)&(File.Year== (year - lag)), 'Returns')].values[0]
            except:
                File.loc[i, col] = None
            
            
            cols.append(col)
            
    File.dropna(inplace=True)
    File[cols] = np.where(File[cols] > 0, 1, 0)
    File['Direction'] = np.where(File['Returns'] > 0, 1, -1)
    return display_all(File)

In [7]:
data = clean(eu)

In [8]:
feat(data)

,Date,Close,Year,Week_day,Day_name,Week,Returns,feat_1,feat_2,feat_3,feat_4,feat_5,Direction
1226,2016-09-07,10744.05,2016,2,Wednesday,36,0.004683,1,1,1,1,1,1
1227,2016-09-08,10669.85,2016,3,Thursday,36,-0.006930,1,1,1,1,0,-1
1228,2016-09-09,10496.05,2016,4,Friday,36,-0.016423,0,1,1,1,0,-1
1229,2016-09-12,10540.35,2016,0,Monday,37,0.004212,1,0,1,0,0,1
1230,2016-09-13,10412.35,2016,1,Tuesday,37,-0.012218,1,0,1,1,1,-1
1231,2016-09-14,10362.55,2016,2,Wednesday,37,-0.004794,0,1,1,1,1,-1
1232,2016-09-15,10455.85,2016,3,Thursday,37,0.008963,1,0,0,1,1,1
1233,2016-09-16,10295.55,2016,4,Friday,37,-0.015450,0,0,1,1,1,-1
1234,2016-09-19,10344.35,2016,0,Monday,38,0.004729,0,1,1,0,0,1
1235,2016-09-20,10401.35,2016,1,Tuesday,38,0.005495,1,1,1,0,1,1
1236,2016-09-21,10507.05,2016,2,Wednesday,38,0.010111,1,1,1,1,0,1
1237,2016-09-22,10673.55,2016,3,Thursday,38,0.015722,0,1,0,1,0,1
1238,2016-09-23,10618.55,2016,4,Friday,38,-0.005166,0,1,0,1,1,-1
1253,2016-10-17,10507.35,2016,0,Monday,42,-0.007443,0,0,1,0,0,-1
1254,2016-10-18,10626.35,2016,1,Tuesday,42,0.011262,0,1,1,0,1,1
1258,2016-10-24,10774.35,2016,0,Monday,43,0.005398,1,0,1,1,1,1
1259,2016-10-25,10768.35,2016,1,Tuesday,43,-0.000557,0,1,1,0,0,-1
1261,2016-10-27,10705.85,2016,3,Thursday,43,0.001215,1,1,1,0,1,1
1262,2016-10-28,10650.35,2016,4,Friday,43,-0.005198,1,0,1,1,0,-1
1274,2016-11-15,10757.85,2016,1,Tuesday,46,0.004687,1,1,0,0,1,1
1288,2016-12-05,10711.35,2016,0,Monday,49,0.017517,1,0,0,1,1,1
1289,2016-12-06,10830.55,2016,1,Tuesday,49,0.011067,0,1,0,1,0,1
1290,2016-12-07,11044.85,2016,2,Wednesday,49,0.019593,0,1,0,1,0,1
1291,2016-12-08,11173.85,2016,3,Thursday,49,0.011612,0,0,0,1,0,1
1292,2016-12-09,11231.05,2016,4,Friday,49,0.005106,1,1,1,0,1,1
1293,2016-12-12,11167.55,2016,0,Monday,50,-0.005670,1,0,0,1,0,-1
1294,2016-12-13,11277.35,2016,1,Tuesday,50,0.009784,0,0,0,1,0,1
1295,2016-12-14,11233.35,2016,2,Wednesday,50,-0.003909,0,0,0,1,0,-1
1296,2016-12-15,11372.55,2016,3,Thursday,50,0.012316,1,1,0,0,1,1
1297,2016-12-16,11388.05,2016,4,Friday,50,0.001362,0,0,1,1,0,1
1298,2016-12-19,11395.85,2016,0,Monday,51,0.000685,1,0,1,1,0,1
1299,2016-12-20,11455.35,2016,1,Tuesday,51,0.005208,1,1,0,1,1,1
1300,2016-12-21,11459.85,2016,2,Wednesday,51,0.000393,1,1,1,0,0,1
1301,2016-12-22,11446.35,2016,3,Thursday,51,-0.001179,1,1,1,1,1,-1
1302,2016-12-23,11452.35,2016,4,Friday,51,0.000524,0,0,1,0,1,1
1310,2017-01-06,11604.35,2017,4,Friday,1,0.003021,0,0,1,1,0,1
1311,2017-01-09,11553.45,2017,0,Monday,2,-0.004396,1,0,1,0,0,-1
1312,2017-01-10,11569.95,2017,1,Tuesday,2,0.001427,1,0,1,0,1,1
1313,2017-01-11,11654.45,2017,2,Wednesday,2,0.007277,0,1,0,1,1,1
1314,2017-01-12,11563.95,2017,3,Thursday,2,-0.007796,1,1,0,1,1,-1
1315,2017-01-13,11608.85,2017,4,Friday,2,0.003875,0,0,1,0,0,1
1316,2017-01-16,11555.85,2017,0,Monday,3,-0.004576,1,1,0,1,1,-1
1317,2017-01-17,11550.55,2017,1,Tuesday,3,-0.000459,1,1,1,0,1,-1
1318,2017-01-18,11620.55,2017,2,Wednesday,3,0.006042,0,1,1,0,1,1
1319,2017-01-19,11572.75,2017,3,Thursday,3,-0.004122,1,1,0,1,1,-1
1320,2017-01-20,11618.35,2017,4,Friday,3,0.003933,1,1,0,0,1,1
1321,2017-01-23,11567.75,2017,0,Monday,4,-0.004365,0,0,1,1,0,-1
1322,2017-01-24,11628.55,2017,1,Tuesday,4,0.005242,1,1,1,0,0,1
1323,2017-01-25,11816.85,2017,2,Wednesday,4,0.016063,0,1,0,1,1,1
1324,2017-01-26,11832.65,2017,3,Thursday,4,0.001336,0,1,0,1,1,1
1325,2017-01-27,11809.75,2017,4,Friday,4,-0.001937,1,1,0,1,1,-1
1326,2017-01-30,11712.25,2017,0,Monday,5,-0.008290,0,1,0,0,0,-1
1327,2017-01-31,11584.15,2017,1,Tuesday,5,-0.010998,0,0,1,1,1,-1
1328,2017-02-01,11660.05,2017,2,Wednesday,5,0.006531,1,0,0,0,1,1
1329,2017-02-02,11653.65,2017,3,Thursday,5,-0.000549,0,1,1,0,1,-1
1330,2017-02-03,11659.65,2017,4,Friday,5,0.000515,0,0,0,1,1,1
1331,2017-02-06,11510.25,2017,0,Monday,6,-0.012896,0,1,0,0,0,-1
1332,2017-02-07,11559.35,2017,1,Tuesday,6,0.004257,0,1,1,1,0,1
1333,2017-02-08,11549.95,2017,2,Wednesday,6,-0.000814,1,0,0,0,1,-1
1334,2017-02-09,11643.30,2017,3,Thursday,6,0.008050,0,1,1,1,1,1
1335,2017-02-10,11664.85,2017,4,Friday,6,0.001849,1,0,1,1,0,1
1336,2017-02-13,11771.60,2017,0,Monday,7,0.009110,1,0,0,0,1,1
1337,2017-02-14,11793.86,2017,1,Tuesday,7,0.001889,1,1,1,1,0,1
1338,2017-02-15,11791.10,2017,2,Wednesday,7,-0.000234,1,0,1,1,0,-1
1339,2017-02-16,11770.85,2017,3,Thursday,7,-0.001719,1,1,1,0,1,-1
1340,2017-02-17,11786.65,2017,4,Friday,7,0.001341,0,1,1,0,1,1
1341,2017-02-20,11824.30,2017,0,Monday,8,0.003189,1,0,0,1,1,1
1342,2017-02-21,11990.75,2017,1,Tuesday,8,0.013979,0,1,0,1,0,1
1343,2017-02-22,12001.60,2017,2,Wednesday,8,0.000904,0,1,0,0,0,1
1344,2017-02-23,11955.85,2017,3,Thursday,8,-0.003819,1,1,1,0,0,-1
1345,2017-02-24,11832.35,2017,4,Friday,8,-0.010383,1,1,1,1,1,-1
1346,2017-02-27,11849.75,2017,0,Monday,9,0.001469,0,0,1,0,0,1
1347,2017-02-28,11828.15,2017,1,Tuesday,9,-0.001824,1,1,0,1,1,-1
1348,2017-03-01,12071.25,2017,2,Wednesday,9,0.020344,1,0,0,1,0,1
1349,2017-03-02,12045.60,2017,3,Thursday,9,-0.002127,1,1,0,1,1,-1
1350,2017-03-03,12014.60,2017,4,Friday,9,-0.002577,1,1,1,0,0,-1
1351,2017-03-06,11978.85,2017,0,Monday,10,-0.002980,0,1,0,1,0,-1
1352,2017-03-07,11954.85,2017,1,Tuesday,10,-0.002006,0,0,1,1,0,-1
1353,2017-03-08,11942.85,2017,2,Wednesday,10,-0.001004,1,1,0,1,1,-1
1354,2017-03-09,11985.93,2017,3,Thursday,10,0.003601,0,1,0,1,1,1
1355,2017-03-10,11959.39,2017,4,Friday,10,-0.002217,1,1,0,1,1,-1
1356,2017-03-13,12013.08,2017,0,Monday,11,0.004479,1,1,0,1,1,1
1357,2017-03-14,11991.15,2017,1,Tuesday,11,-0.001827,0,0,0,0,1,-1
1358,2017-03-15,12056.75,2017,2,Wednesday,11,0.005456,1,1,0,1,1,1
1359,2017-03-16,12078.45,2017,3,Thursday,11,0.001798,0,1,0,1,1,1
1360,2017-03-17,12077.45,2017,4,Friday,11,-0.000083,1,1,1,0,1,-1
1361,2017-03-20,12043.25,2017,0,Monday,12,-0.002836,1,1,1,0,0,-1
1362,2017-03-21,11905.80,2017,1,Tuesday,12,-0.011479,1,0,1,0,0,-1
1363,2017-03-22,11928.76,2017,2,Wednesday,12,0.001927,1,0,0,1,0,1
1364,2017-03-23,12014.05,2017,3,Thursday,12,0.007125,0,1,1,0,0,1
1367,2017-03-28,12176.05,2017,1,Tuesday,13,0.012279,1,1,1,1,0,1
1368,2017-03-29,12200.85,2017,2,Wednesday,13,0.002035,1,0,1,0,0,1
1369,2017-03-30,12255.10,2017,3,Thursday,13,0.004437,0,1,1,1,0,1
1372,2017-04-04,12293.95,2017,1,Tuesday,14,0.000863,0,0,1,1,0,1
1373,2017-04-05,12173.45,2017,2,Wednesday,14,-0.009850,1,1,1,0,0,-1
1374,2017-04-06,12219.85,2017,3,Thursday,14,0.003804,0,0,0,0,0,1
1377,2017-04-11,12181.26,2017,1,Tuesday,15,-0.000264,1,1,0,0,0,-1
1378,2017-04-12,12134.35,2017,2,Wednesday,15,-0.003858,1,0,1,1,1,-1
1379,2017-04-13,12085.88,2017,3,Thursday,15,-0.004002,1,1,0,1,1,-1
1380,2017-04-18,11994.36,2017,1,Tuesday,16,-0.007601,1,0,0,1,1,-1
1381,2017-04-19,11974.29,2017,2,Wednesday,16,-0.001675,1,0,1,0,0,-1
1382,2017-04-20,12039.96,2017,3,Thursday,16,0.005469,0,0,1,0,0,1
1385,2017-04-25,12474.30,2017,1,Tuesday,17,0.000882,0,1,1,1,1,1
1386,2017-04-26,12431.81,2017,2,Wednesday,17,-0.003412,1,0,0,1,1,-1
1387,2017-04-27,12441.46,2017,3,Thursday,17,0.000776,0,0,0,1,1,1
1388,2017-04-28,12430.70,2017,4,Friday,17,-0.000865,0,1,0,1,1,-1
1393,2017-05-08,12704.20,2017,0,Monday,19,-0.008544,1,1,0,1,1,-1
1394,2017-05-09,12744.45,2017,1,Tuesday,19,0.003163,1,0,0,1,0,1
1395,2017-05-10,12765.92,2017,2,Wednesday,19,0.001683,0,1,1,1,0,1
1396,2017-05-11,12737.95,2017,3,Thursday,19,-0.002193,0,1,1,0,1,-1
1397,2017-05-12,12775.49,2017,4,Friday,19,0.002943,1,1,1,1,1,1
1399,2017-05-16,12800.94,2017,1,Tuesday,20,-0.000397,0,0,1,1,0,-1
1400,2017-05-17,12543.45,2017,2,Wednesday,20,-0.020320,1,0,0,1,0,-1
1401,2017-05-18,12610.93,2017,3,Thursday,20,0.005365,0,1,0,0,0,1
1402,2017-05-19,12619.45,2017,4,Friday,20,0.000675,1,0,0,1,0,1
1403,2017-05-22,12628.20,2017,0,Monday,21,0.000693,0,1,1,0,1,1
1404,2017-05-23,12667.26,2017,1,Tuesday,21,0.003088,1,1,0,1,1,1
1405,2017-05-24,12644.21,2017,2,Wednesday,21,-0.001821,1,1,1,0,0,-1
1406,2017-05-25,12619.99,2017,3,Thursday,21,-0.001917,1,1,1,0,0,-1
1407,2017-05-26,12594.22,2017,4,Friday,21,-0.002044,1,0,1,0,1,-1
1409,2017-05-30,12587.90,2017,1,Tuesday,22,-0.003124,0,0,1,1,1,-1
1410,2017-05-31,12631.95,2017,2,Wednesday,22,0.003493,0,1,0,0,0,1
1411,2017-06-01,12694.85,2017,3,Thursday,22,0.004967,1,0,1,1,0,1
1412,2017-06-02,12863.05,2017,4,Friday,22,0.013162,0,0,0,0,0,1
1413,2017-06-06,12665.05,2017,1,Tuesday,23,-0.015513,1,0,0,0,0,-1
1414,2017-06-07,12695.20,2017,2,Wednesday,23,0.002378,0,1,1,0,1,1
1415,2017-06-08,12730.20,2017,3,Thursday,23,0.002753,0,0,1,0,0,1
1416,2017-06-09,12760.62,2017,4,Friday,23,0.002387,0,0,1,1,1,1
1417,2017-06-12,12704.60,2017,0,Monday,24,-0.004400,0,0,1,1,0,-1
1418,2017-06-13,12798.97,2017,1,Tuesday,24,0.007401,0,0,1,0,1,1
1419,2017-06-14,12835.38,2017,2,Wednesday,24,0.002841,1,1,0,0,0,1
1420,2017-06-15,12697.50,2017,3,Thursday,24,-0.010800,1,1,0,1,1,-1
1421,2017-06-16,12751.18,2017,4,Friday,24,0.004219,1,0,0,0,1,1
1422,2017-06-19,12907.57,2017,0,Monday,25,0.012190,1,0,0,1,0,1
1423,2017-06-20,12810.22,2017,1,Tuesday,25,-0.007571,1,1,1,1,1,-1
1424,2017-06-21,12764.66,2017,2,Wednesday,25,-0.003563,0,0,1,0,1,-1
1425,2017-06-22,12773.50,2017,3,Thursday,25,0.000692,1,1,1,0,0,1
1426,2017-06-23,12713.48,2017,4,Friday,25,-0.004710,0,0,0,0,1,-1
1427,2017-06-26,12769.88,2017,0,Monday,26,0.004426,0,1,0,0,0,1
1428,2017-06-27,12596.60,2017,1,Tuesday,26,-0.013662,1,1,0,1,1,-1
1429,2017-06-28,12672.53,2017,2,Wednesday,26,0.006010,1,0,0,1,1,1
1430,2017-06-29,12401.57,2017,3,Thursday,26,-0.021614,1,1,0,1,0,-1
1431,2017-06-30,12385.81,2017,4,Friday,26,-0.001272,1,1,1,0,1,-1
1432,2017-07-03,12442.75,2017,0,Monday,27,0.004587,0,0,0,1,1,1
1433,2017-07-04,12445.80,2017,1,Tuesday,27,0.000245,0,1,1,0,1,1
1434,2017-07-05,12484.16,2017,2,Wednesday,27,0.003077,0,1,1,0,0,1
1435,2017-07-06,12347.60,2017,3,Thursday,27,-0.010999,0,0,1,1,0,-1
1436,2017-07-07,12419.06,2017,4,Friday,27,0.005771,1,0,0,0,0,1
1437,2017-07-10,12456.20,2017,0,Monday,28,0.002986,1,0,0,1,0,1
1438,2017-07-11,12485.30,2017,1,Tuesday,28,0.002333,1,1,0,1,1,1
1439,2017-07-12,12635.15,2017,2,Wednesday,28,0.011931,0,0,1,0,1,1
1440,2017-07-13,12653.50,2017,3,Thursday,28,0.001451,1,1,0,1,0,1
1441,2017-07-14,12657.55,2017,4,Friday,28,0.000320,1,1,0,1,1,1
1442,2017-07-17,12582.60,2017,0,Monday,29,-0.005939,0,1,1,1,0,-1
1443,2017-07-18,12439.90,2017,1,Tuesday,29,-0.011406,0,1,0,0,1,-1
1444,2017-07-19,12482.80,2017,2,Wednesday,29,0.003443,1,0,1,1,1,1
1445,2017-07-20,12448.00,2017,3,Thursday,29,-0.002792,0,1,0,1,1,-1
1446,2017-07-21,12248.34,2017,4,Friday,29,-0.016170,1,0,1,1,0,-1
1447,2017-07-24,12248.10,2017,0,Monday,30,-0.000020,1,1,0,0,0,-1
1448,2017-07-25,12265.55,2017,1,Tuesday,30,0.001424,1,0,1,0,0,1
1449,2017-07-26,12259.92,2017,2,Wednesday,30,-0.000459,1,0,1,1,1,-1
1450,2017-07-27,12189.30,2017,3,Thursday,30,-0.005777,1,0,1,0,1,-1
1451,2017-07-28,12171.31,2017,4,Friday,30,-0.001477,0,0,0,0,1,-1
1452,2017-07-31,12100.00,2017,0,Monday,31,-0.005876,0,0,0,0,0,-1
1453,2017-08-01,12253.00,2017,1,Tuesday,31,0.012565,0,1,1,0,0,1
1454,2017-08-02,12185.00,2017,2,Wednesday,31,-0.005565,1,1,0,1,0,-1
1455,2017-08-03,12141.35,2017,3,Thursday,31,-0.003589,1,1,0,1,0,-1
1456,2017-08-04,12284.06,2017,4,Friday,31,0.011686,1,1,0,0,1,1
1457,2017-08-07,12250.60,2017,0,Monday,32,-0.002728,1,1,1,0,1,-1
1458,2017-08-08,12241.62,2017,1,Tuesday,32,-0.000733,1,1,0,0,1,-1
1459,2017-08-09,12177.55,2017,2,Wednesday,32,-0.005248,0,1,1,0,0,-1
1460,2017-08-10,11957.09,2017,3,Thursday,32,-0.018270,1,0,0,1,0,-1
1461,2017-08-11,11997.30,2017,4,Friday,32,0.003357,0,0,1,1,1,1
1462,2017-08-14,12162.73,2017,0,Monday,33,0.013695,1,1,1,1,0,1
1463,2017-08-15,12196.97,2017,1,Tuesday,33,0.002811,0,0,0,1,1,1
1464,2017-08-16,12234.00,2017,2,Wednesday,33,0.003031,0,0,1,0,0,1
1465,2017-08-17,12120.07,2017,3,Thursday,33,-0.009356,0,0,1,0,1,-1
1466,2017-08-18,12167.05,2017,4,Friday,33,0.003869,0,1,0,1,1,1
1467,2017-08-21,12070.30,2017,0,Monday,34,-0.007984,0,0,1,0,0,-1
1468,2017-08-22,12251.75,2017,1,Tuesday,34,0.014921,1,0,1,0,1,1
1469,2017-08-23,12184.70,2017,2,Wednesday,34,-0.005488,1,0,0,0,0,-1
1470,2017-08-24,12177.65,2017,3,Thursday,34,-0.000579,0,0,1,1,0,-1
1471,2017-08-25,12177.85,2017,4,Friday,34,0.000016,1,0,0,1,1,1
1472,2017-08-28,12127.70,2017,0,Monday,35,-0.004127,1,0,1,0,1,-1
1473,2017-08-29,11985.29,2017,1,Tuesday,35,-0.011812,1,1,1,0,0,-1
1474,2017-08-30,12020.91,2017,2,Wednesday,35,0.002968,0,1,0,0,1,1
1475,2017-08-31,12062.81,2017,3,Thursday,35,0.003480,0,1,0,1,0,1
1476,2017-09-01,12153.43,2017,4,Friday,35,0.007484,1,0,1,0,1,1
1477,2017-09-04,12124.75,2017,0,Monday,36,-0.002363,0,0,1,1,1,-1
1478,2017-09-05,12069.80,2017,1,Tuesday,36,-0.004542,1,0,1,0,0,-1
1479,2017-09-06,12283.20,2017,2,Wednesday,36,0.017526,1,1,1,1,1,1
1480,2017-09-07,12317.82,2017,3,Thursday,36,0.002815,0,1,1,1,1,1
1481,2017-09-08,12284.89,2017,4,Friday,36,-0.002677,0,0,1,1,1,-1
1482,2017-09-11,12497.10,2017,0,Monday,37,0.017127,1,1,0,1,0,1
1483,2017-09-12,12519.65,2017,1,Tuesday,37,0.001803,0,1,0,1,1,1
1484,2017-09-13,12553.15,2017,2,Wednesday,37,0.002672,0,0,1,1,1,1
1485,2017-09-14,12548.80,2017,3,Thursday,37,-0.000347,1,1,0,0,1,-1
1486,2017-09-15,12534.09,2017,4,Friday,37,-0.001173,0,0,0,1,1,-1
1487,2017-09-18,12565.30,2017,0,Monday,38,0.002487,1,0,1,1,0,1
1488,2017-09-19,12559.64,2017,1,Tuesday,38,-0.000451,1,1,1,1,0,-1
1489,2017-09-20,12641.10,2017,2,Wednesday,38,0.006465,1,1,1,1,1,1
1490,2017-09-21,12599.30,2017,3,Thursday,38,-0.003312,1,0,1,0,1,-1
1491,2017-09-22,12612.37,2017,4,Friday,38,0.001037,0,0,1,0,1,1
1506,2017-10-16,13004.85,2017,0,Monday,42,0.000350,0,0,0,1,0,1
1507,2017-10-17,13012.41,2017,1,Tuesday,42,0.000581,1,0,1,1,0,1
1511,2017-10-23,12989.00,2017,0,Monday,43,-0.000678,1,1,0,1,1,-1
1512,2017-10-24,13023.40,2017,1,Tuesday,43,0.002645,0,0,1,1,0,1
1514,2017-10-26,13165.14,2017,3,Thursday,43,0.014509,1,1,1,1,0,1
1515,2017-10-27,13230.75,2017,4,Friday,43,0.004971,0,1,0,1,1,1
1526,2017-11-14,13036.45,2017,1,Tuesday,46,-0.005247,1,1,1,0,0,-1
1540,2017-12-04,13027.35,2017,0,Monday,49,0.005596,1,1,0,0,1,1
1541,2017-12-05,13002.40,2017,1,Tuesday,49,-0.001917,1,0,1,0,1,-1
1542,2017-12-06,12999.77,2017,2,Wednesday,49,-0.000202,1,0,1,0,1,-1
1543,2017-12-07,13094.52,2017,3,Thursday,49,0.007262,1,0,0,0,1,1
1544,2017-12-08,13166.80,2017,4,Friday,49,0.005505,1,1,1,1,0,1
1545,2017-12-11,13153.28,2017,0,Monday,50,-0.001027,0,1,0,0,1,-1
1546,2017-12-12,13170.30,2017,1,Tuesday,50,0.001293,1,0,0,0,1,1
1547,2017-12-13,13074.00,2017,2,Wednesday,50,-0.007339,0,0,0,0,1,-1
1548,2017-12-14,13030.50,2017,3,Thursday,50,-0.003333,1,1,1,0,0,-1
1549,2017-12-15,13123.35,2017,4,Friday,50,0.007100,1,0,0,1,1,1
1550,2017-12-18,13311.84,2017,0,Monday,51,0.014261,1,1,0,1,1,1
1551,2017-12-19,13229.05,2017,1,Tuesday,51,-0.006239,1,1,1,0,1,-1
1552,2017-12-20,13071.50,2017,2,Wednesday,51,-0.011981,1,1,1,1,0,-1
1553,2017-12-21,13071.30,2017,3,Thursday,51,-0.000015,0,1,1,1,1,-1
1554,2017-12-22,13076.60,2017,4,Friday,51,0.000405,1,0,0,1,0,1
1561,2018-01-05,13337.24,2018,4,Friday,1,0.012657,1,0,0,1,1,1
1562,2018-01-08,13371.30,2018,0,Monday,2,0.002550,0,1,0,1,0,1
1563,2018-01-09,13397.70,2018,1,Tuesday,2,0.001972,1,1,0,1,0,1
1564,2018-01-10,13263.96,2018,2,Wednesday,2,-0.010032,1,0,1,0,1,-1
1565,2018-01-11,13244.20,2018,3,Thursday,2,-0.001491,0,1,1,0,1,-1
1566,2018-01-12,13237.40,2018,4,Friday,2,-0.000514,1,0,0,1,0,-1
1567,2018-01-15,13195.25,2018,0,Monday,3,-0.003189,0,1,1,0,1,-1
1568,2018-01-16,13149.05,2018,1,Tuesday,3,-0.003507,0,1,1,1,0,-1
1569,2018-01-17,13239.30,2018,2,Wednesday,3,0.006840,1,0,1,1,0,1
1570,2018-01-18,13284.32,2018,3,Thursday,3,0.003395,0,1,1,0,1,1
1571,2018-01-19,13464.83,2018,4,Friday,3,0.013497,1,1,1,0,0,1
1572,2018-01-22,13505.80,2018,0,Monday,4,0.003038,0,0,0,1,1,1
1573,2018-01-23,13572.55,2018,1,Tuesday,4,0.004930,1,1,1,1,0,1
1574,2018-01-24,13424.34,2018,2,Wednesday,4,-0.010980,1,0,1,0,1,-1
1575,2018-01-25,13317.80,2018,3,Thursday,4,-0.007968,1,0,1,0,1,-1
1576,2018-01-26,13387.30,2018,4,Friday,4,0.005205,0,1,1,0,1,1
1577,2018-01-29,13308.34,2018,0,Monday,5,-0.005916,0,0,1,0,0,-1
1578,2018-01-30,13197.05,2018,1,Tuesday,5,-0.008398,0,0,0,1,1,-1
1579,2018-01-31,13198.30,2018,2,Wednesday,5,0.000095,1,1,0,0,0,1
1580,2018-02-01,12965.80,2018,3,Thursday,5,-0.017773,0,0,1,1,0,-1
1581,2018-02-02,12709.30,2018,4,Friday,5,-0.019981,1,0,0,0,1,-1
1582,2018-02-05,12265.30,2018,0,Monday,6,-0.035560,0,0,1,0,0,-1
1583,2018-02-06,12646.60,2018,1,Tuesday,6,0.030614,1,0,1,1,1,1
1584,2018-02-07,12534.05,2018,2,Wednesday,6,-0.008939,0,1,0,0,0,-1
1585,2018-02-08,12131.30,2018,3,Thursday,6,-0.032660,1,0,1,1,1,-1
1586,2018-02-09,12211.60,2018,4,Friday,6,0.006597,1,1,0,1,1,1
1587,2018-02-12,12349.80,2018,0,Monday,7,0.011254,1,1,0,0,0,1
1588,2018-02-13,12253.30,2018,1,Tuesday,7,-0.007845,1,1,1,1,1,-1
1589,2018-02-14,12415.80,2018,2,Wednesday,7,0.013175,0,1,0,1,1,1
1590,2018-02-15,12358.34,2018,3,Thursday,7,-0.004639,0,1,1,1,0,-1
1591,2018-02-16,12486.84,2018,4,Friday,7,0.010344,1,0,1,1,0,1
1592,2018-02-19,12394.33,2018,0,Monday,8,-0.007436,1,1,0,0,1,-1
1593,2018-02-20,12430.81,2018,1,Tuesday,8,0.002939,1,0,1,0,1,1
1594,2018-02-21,12394.30,2018,2,Wednesday,8,-0.002941,1,0,1,0,0,-1
1595,2018-02-22,12426.80,2018,3,Thursday,8,0.002619,0,1,1,1,0,1
1596,2018-02-23,12544.09,2018,4,Friday,8,0.009394,0,1,1,1,1,1
1597,2018-02-26,12584.81,2018,0,Monday,9,0.003241,1,0,0,1,0,1
1598,2018-02-27,12430.81,2018,1,Tuesday,9,-0.012312,0,1,1,0,1,-1
1599,2018-02-28,12366.80,2018,2,Wednesday,9,-0.005163,1,1,0,0,1,-1
1600,2018-03-01,12063.71,2018,3,Thursday,9,-0.024814,0,1,1,0,1,-1
1601,2018-03-02,12001.31,2018,4,Friday,9,-0.005186,0,1,1,1,0,-1
1602,2018-03-05,12168.85,2018,0,Monday,10,0.013864,0,0,1,0,1,1
1603,2018-03-06,12158.05,2018,1,Tuesday,10,-0.000888,0,0,0,1,1,-1
1604,2018-03-07,12262.71,2018,2,Wednesday,10,0.008571,0,1,1,0,1,1
1605,2018-03-08,12351.34,2018,3,Thursday,10,0.007202,1,0,1,0,1,1
1606,2018-03-09,12371.70,2018,4,Friday,10,0.001647,0,1,1,0,1,1
1607,2018-03-12,12399.73,2018,0,Monday,11,0.002263,1,1,1,0,1,1
1608,2018-03-13,12153.45,2018,1,Tuesday,11,-0.020062,0,0,0,0,0,-1
1609,2018-03-14,12256.73,2018,2,Wednesday,11,0.008462,1,1,1,0,1,1
1610,2018-03-15,12383.20,2018,3,Thursday,11,0.010266,1,0,1,0,1,1
1611,2018-03-16,12403.47,2018,4,Friday,11,0.001636,0,1,1,1,0,1
1612,2018-03-19,12248.18,2018,0,Monday,12,-0.012599,0,1,1,1,0,-1
1613,2018-03-20,12346.20,2018,1,Tuesday,12,0.007971,0,1,0,1,0,1
1614,2018-03-21,12263.95,2018,2,Wednesday,12,-0.006684,1,1,0,0,1,-1
1615,2018-03-22,11991.50,2018,3,Thursday,12,-0.022466,1,0,1,1,0,-1
1618,2018-03-27,11853.70,2018,1,Tuesday,13,-0.005555,1,1,1,1,1,-1
1619,2018-03-28,11942.09,2018,2,Wednesday,13,0.007429,1,1,0,1,0,1
1620,2018-03-29,12120.29,2018,3,Thursday,13,0.014812,1,0,1,1,1,1
1621,2018-04-03,12056.13,2018,1,Tuesday,14,-0.005308,1,0,0,1,1,-1
1622,2018-04-04,12070.00,2018,2,Wednesday,14,0.001150,0,1,1,1,0,1
1623,2018-04-05,12282.73,2018,3,Thursday,14,0.017471,1,0,0,0,0,1
1626,2018-04-10,12382.81,2018,1,Tuesday,15,0.011883,0,1,1,0,0,1
1627,2018-04-11,12279.69,2018,2,Wednesday,15,-0.008363,0,1,0,1,1,-1
1628,2018-04-12,12431.20,2018,3,Thursday,15,0.012263,0,1,1,0,1,1
1631,2018-04-17,12586.50,2018,1,Tuesday,16,0.013258,0,1,0,0,1,1
1632,2018-04-18,12597.01,2018,2,Wednesday,16,0.000835,0,1,0,1,0,1
1633,2018-04-19,12559.70,2018,3,Thursday,16,-0.002966,1,0,0,1,0,-1
1636,2018-04-24,12445.17,2018,1,Tuesday,17,-0.010032,1,0,1,1,1,-1
1637,2018-04-25,12449.05,2018,2,Wednesday,17,0.000312,0,1,0,0,1,1
1638,2018-04-26,12561.39,2018,3,Thursday,17,0.008984,1,0,0,0,1,1
1639,2018-04-27,12589.69,2018,4,Friday,17,0.002250,0,0,1,0,1,1
1644,2018-05-07,12927.29,2018,0,Monday,19,0.006799,0,1,1,0,1,1
1645,2018-05-08,12937.40,2018,1,Tuesday,19,0.000782,1,1,0,0,1,1
1646,2018-05-09,12978.49,2018,2,Wednesday,19,0.003171,1,0,1,1,1,1
1647,2018-05-10,13028.21,2018,3,Thursday,19,0.003824,0,0,1,1,0,1
1648,2018-05-11,12985.89,2018,4,Friday,19,-0.003254,1,1,1,1,1,-1
1650,2018-05-15,12990.73,2018,1,Tuesday,20,0.001630,0,0,0,1,1,1
1651,2018-05-16,13016.85,2018,2,Wednesday,20,0.002009,0,1,0,0,1,1
1652,2018-05-17,13104.53,2018,3,Thursday,20,0.006713,1,0,1,0,0,1
1653,2018-05-18,13069.27,2018,4,Friday,20,-0.002694,1,1,0,0,1,-1
1654,2018-05-22,13155.27,2018,1,Tuesday,21,0.006559,1,1,1,0,1,1

In [11]:
cols = ['feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5']
data[cols + ['Direction']].head()

      feat_1  feat_2  feat_3  feat_4  feat_5  Direction
1226       1       1       1       1       1          1
1227       1       1       1       1       0         -1
1228       0       1       1       1       0         -1
1229       1       0       1       0       0          1
1230       1       0       1       1       1         -1

## *MACHINE LEARNING*

#### **Random Forest**

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

C:\Users\Siseng Consulting\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [13]:
split = int(len(data) * 0.75)
train = data.iloc[:split].copy()
test = data.iloc[split:].copy()

In [61]:
model = RandomForestClassifier(n_estimators=10,n_jobs=-1, min_samples_leaf=43)
#train[cols] = sc.fit_transform(train[cols])
#test[cols] = sc.transform(test[cols])
model.fit(train[cols], train['Direction'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=43, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [62]:
accuracy_score(train['Direction'], model.predict(train[cols]))

0.5484949832775919

In [63]:
test['Position'] = model.predict(test[cols])
accuracy_score(test['Direction'], test['Position'])

0.55